_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 83
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 83
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.9
            "5": 0.19.4
            "6": 4.48.3
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
Iteration:
    value: 5000
batch_real:
    value: 16
batch_syn:
    value: null
batch_train:
    value: 256
buffer_path:
    value: null
data_path:
    value: distill_utils/data
dataset:
    value: HMDB51
device:
    value: cuda
dis_metric:
    value: ours
epoch_eval_train:
    value: 500
eval_it:
    value: 500
eval_mode:
    value: SS
expert_epochs:
    value: 3
frames:
    value: 16
init:
    value: real
inner_loop:
    value: 1
ipc:
    value: 1
lr_img:
    value: 30
lr_lr:
    value: 1e-05
lr_net:
    value: 0.01
lr_teacher:
    value: 0.001
max_start_epoch:
    value: 25
method:
    value: DM
model:
    value: ConvNet3D
num_eval:
    value: 1
num_workers:
    value: 4
outer_loop:
    value: 1
preload:
    value: true
save_path:
    value: ./logged_files
syn_steps:
    value: 64
train_lr:
    value: false
vae_path:
    value: ./vae_weights
